[workspace]
resolver = "2"
members = [
    "desert",
    "desert_benchmarks",
    "desert_core",
    "desert_macro",
    "github",
]

[workspace.dependencies]
test-r = "2.3.1"

# Enable when profiling
#[profile.release]
#debug = true
